const ORACLE_TYPE_CHAINLINK_MAIN_ASSET = 5;
const ORACLE_TYPE_WRAPPED_TO_UNDERLYING = 11;

const PARAM_FORCE_TRANSFER_ASSET_TO_OWNER_ON_LIQUIDATION = 0;
const PARAM_FORCE_MOVE_WRAPPED_ASSET_POSITION_ON_LIQUIDATION = 1;

module.exports = {
	ORACLE_TYPE_CHAINLINK_MAIN_ASSET,
    ORACLE_TYPE_WRAPPED_TO_UNDERLYING,
    PARAM_FORCE_TRANSFER_ASSET_TO_OWNER_ON_LIQUIDATION,
    PARAM_FORCE_MOVE_WRAPPED_ASSET_POSITION_ON_LIQUIDATION,
};
