const ORACLE_TYPE_UNISWAP_V2_MAIN_ASSET_KEYDONIX = 1;
const ORACLE_TYPE_UNISWAP_V2_POOL_TOKEN_KEYDONIX = 2;
const ORACLE_TYPE_CHAINLINK_MAIN_ASSET = 5;
const ORACLE_TYPE_WRAPPED_TO_UNDERLYING = 11;
const ORACLE_TYPE_UNISWAP_V2_POOL_TOKEN = 12;
const ORACLE_TYPE_WRAPPED_TO_UNDERLYING_KEYDONIX = 19;

const KEYDONIX_ORACLES_TYPES = [
    ORACLE_TYPE_UNISWAP_V2_MAIN_ASSET_KEYDONIX,
    ORACLE_TYPE_UNISWAP_V2_POOL_TOKEN_KEYDONIX,
    ORACLE_TYPE_WRAPPED_TO_UNDERLYING_KEYDONIX,
];

const PARAM_FORCE_TRANSFER_ASSET_TO_OWNER_ON_LIQUIDATION = 0;
const PARAM_FORCE_MOVE_WRAPPED_ASSET_POSITION_ON_LIQUIDATION = 1;

module.exports = {
    ORACLE_TYPE_UNISWAP_V2_MAIN_ASSET_KEYDONIX,
    ORACLE_TYPE_UNISWAP_V2_POOL_TOKEN_KEYDONIX,
	ORACLE_TYPE_CHAINLINK_MAIN_ASSET,
    ORACLE_TYPE_WRAPPED_TO_UNDERLYING,
    ORACLE_TYPE_UNISWAP_V2_POOL_TOKEN,
    ORACLE_TYPE_WRAPPED_TO_UNDERLYING_KEYDONIX,

    KEYDONIX_ORACLES_TYPES,

    PARAM_FORCE_TRANSFER_ASSET_TO_OWNER_ON_LIQUIDATION,
    PARAM_FORCE_MOVE_WRAPPED_ASSET_POSITION_ON_LIQUIDATION,
};
